name: blackbox-tutorial2
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python        =3.7
  - pip    
  - pandas       >=0.24.2,   <0.25
  - numpy        >=1.16.1,   <2
  - matplotlib   >=2.1,      <3
  - shap          =0.28.5
  - lime          =0.1.1.33, <0.2
  - eli5         >=0.8.1,    <0.9
  - scikit-learn >=0.20.3,   <0.21
  - scikit-image  =0.15
  - lightgbm     >=2.2.2,    <3
  - keras        >=2.2.4,    <3
  - jupyter
